name: Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Find project root
        id: find_project
        run: |
          echo "Looking for pubspec.yaml in the repository..."
          if [ -f "pubspec.yaml" ]; then
            echo "Found pubspec.yaml in the root directory."
            echo "PROJECT_ROOT=." >> $GITHUB_ENV
          else
            echo "pubspec.yaml not found in the root directory. Searching subdirectories..."
            PROJECT_ROOT=$(find . -name "pubspec.yaml" -exec dirname {} \; | head -n 1)
            if [ -z "$PROJECT_ROOT" ]; then
              echo "Error: Could not find pubspec.yaml in any subdirectory."
              exit 1
            else
              echo "Found pubspec.yaml in $PROJECT_ROOT"
              echo "PROJECT_ROOT=$PROJECT_ROOT" >> $GITHUB_ENV
            fi
          fi

      - name: Change to project root directory
        run: cd ${{ env.PROJECT_ROOT }}

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests with coverage
        run: flutter test --coverage

      - name: Install lcov
        run: sudo apt-get install lcov

      - name: Generate coverage report
        run: genhtml coverage/lcov.info -o coverage/html

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage/lcov.info
          coveralls-token: ${{ secrets.COVERALLS_REPO_TOKEN }}